language: node_js
services:
- docker
- mongodb
branches:
  only:
  - develop
  - master
  - "/^\\d+\\.\\d+\\.\\d+(-rc\\.\\d+)?$/"
git:
  depth: 1
node_js:
- '8'
addons:
  apt:
    sources:
    - google-chrome
    - ubuntu-toolchain-r-test
    packages:
    - google-chrome-stable
    - g++-4.8
  firefox: "latest"
before_cache:
- rm -rf $HOME/build/RocketChat/Rocket.Chat/.meteor/local/log
- rm -rf $HOME/build/RocketChat/Rocket.Chat/.meteor/local/run
- rm -rf $HOME/build/RocketChat/Rocket.Chat/.meteor/local/db
cache:
  directories:
  - "$HOME/node_modules"
  - "$HOME/.meteor"
  - "$HOME/.npm"
  - "$HOME/.node-gyp"
  - "$HOME/build/RocketChat/Rocket.Chat/node_modules"
  - "$HOME/build/RocketChat/Rocket.Chat/.meteor/local"
  - "$HOME/build/RocketChat/Rocket.Chat/packages/rocketchat-livechat/.npm"
  - "$HOME/build/RocketChat/Rocket.Chat/packages/rocketchat-livechat/.app/node_modules"
  - "$HOME/build/RocketChat/Rocket.Chat/packages/rocketchat-livechat/.app/.meteor/local"
before_install:
- if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi
# Start X Virtual Frame Buffer for headless testing with real browsers
- .scripts/start-xvfb.sh
install:
- export PATH="$HOME/.meteor:$PATH"
before_script:
- if [[ $TRAVIS_TAG ]]; then meteor reset; fi
- echo "replication:" | sudo tee -a /etc/mongod.conf
- |-
  echo "  replSetName: \"rs0\"" | sudo tee -a /etc/mongod.conf
- sudo service mongod restart
- mkdir /tmp/build
- meteor --version
- travis_retry git submodule init
- travis_retry git submodule update
- travis_retry meteor npm install
- |-
  mongo --eval 'rs.initiate({_id:"rs0", members: [{"_id":1, "host":"localhost:27017"}]})'
- chmod +x .scripts/smarti.sh
- .scripts/smarti.sh
- meteor npm run lint
- meteor npm run testunit
- meteor npm run stylelint
- travis_wait travis_retry meteor build --headless /tmp/build
- mkdir /tmp/build-test
- tar -xf /tmp/build/Rocket.Chat.tar.gz -C /tmp/build-test/
- cd /tmp/build-test/bundle/programs/server
- npm install
- cd -
- mongo --eval 'rs.status()'
- mongo meteor --eval 'db.getCollectionNames()'
script:
- npm test
# - mongo meteor --eval 'db.dropDatabase()'
# - unset MONGO_OPLOG_URL
# - npm test

before_deploy:
- mkdir -p /tmp/build/rocketchat
- export BUILD_FILE=Assistify_Chat_${TRAVIS_BRANCH/\//_}_${TRAVIS_COMMIT:1}.tar.gz
- mv /tmp/build/Rocket.Chat.tar.gz /tmp/build/rocketchat/${BUILD_FILE}

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: /tmp/build/
  skip_cleanup: true
  on: &1
    repo: assistify/Rocket.Chat
    branch: develop
  bucket: $AWS_BUCKET
  region: $AWS_REGION
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: /tmp/build/
  skip_cleanup: true
  on: &2
    repo: assistify/Rocket.Chat
    branch: master
  bucket: $AWS_BUCKET
  region: $AWS_REGION

after_deploy:
- ./scripts/check-deploy.sh

env:
  global:
    - secure: "OrEXbdizQ8Y/Wp8tPDQNRDliKiJCghmpVT7Ant+PhaW/YOTb8LLmkw1srXbZ0bHklZz97bTpKAVS+3CNjZQjpLbCeAi43Ci7EPR5glKPq5ad/j8Cma6Vn8HvCFD2scX5QRV5P8REsuddwvvEK5wNOZTo7sG/z4zvFmrK3pVfSHnUkvSLfHWd2Z6EEprGuabPql+mRgfIrHWUnEy+R6JZeyj3xZsZjqz/Wg+PgP+ACXQfBTbjY3vw79fg1RcIk8H68sWTyR7jOzPzEI65aPpvVip2cteLOkLW61hDQmTN8QAxzTW/6Fl+Soa/0tWfaWnZgMKpM9r8QYkvJbD1MMiEfpsiSU9tE7tzqc/Z5/HgUDw9CxBOAOFf0dVLs1UgrfaslUgE8oSuT9MARlU691/kgUfD9Saivwiy90J4Kg7vY2sceMe4DcbWA4nUhe0pd4BMDvkl9HiFyuYaXxdYaZqo12/wSHvqgvpZpxOe/xUVzvuFjicpS9JhuUEOjPQ5fGDuqJj96hW/Tm90MU0CpbxMac5HA2oekzFk4o8Dt3rzg1mIzuEofwFmHbQn62kmcAU3qNoK5clR53YbN+8RlmcIN04sSDwE9LwFTExgQwXtuBfVcRhvXZy8MsbhJ5Je3B5N8KdXNMqmuqTwm7MA/NA5tgYfLpvjTEpRKq/Cty7GHpw="
    - secure: "DnL/hAThglne33am1zYDGbYZAJ2yEOXguJHdhafA3YtW+Sryj18F/yMxfE/yZ8De+ko2cwEudLEHnmzlpNtvQBtP7BwBPDJvQQYNaFSlNCTLsWedjMWu5nqrIwh1vnwwlhsamuScRGKDOX4b6mZSzHzKFRA0N7lPAuEpHDhqnAI+L5dRLDHqJ5T0CuEaqh8Uf6TmCug06qEIRSvbKc20tSk6iB6+c8pvmC5lKJ7OxOVyzE75FPqzJS991iYvKt92zAIAKOMEKsM7GIwSLHvMODd0f3u9EDCBKTRblP1Fw8tdCscfLS0/hsoqfg4bgbq3l/lCaAMXVSgepX95K9d81kPdFDbkuOzyNLaTgpf4rZ5l1yFy1qop/wsLCSd8bypIYPvPk7MyFSy0nFNo8gCmipg6FrnGRlMI1g5D5Nk+viLKESzHQUNb+GlR7c/qP9Mdf6MVmpYoVIW3pRIeuOzYtBtFPZa84XOSgcNlTaPKFhegbkfINT9eZx00vCk2P6TW2ucaF+4Pc0TPkThLTvjYyUZu7DxTnSMs3qf+du1Z89VgjnXk90skfj2eEzhObUEpsSEoVcL1kepsrEzaEWZbltaJKJmlhzaa81wNt7UTM4RV4PF+bJ6c4v5ORmg/M2a/IWVJBzZ1TDX4Z6I56cDiJ8DWegsN+SlOyzCR8jpaFuA="
    - secure: "QlUL9l9gL9j7cQNAioS36dTS16iLZIvhtFMH2KLjJkL+6cvqq6e7aFTLAmABofjFMXJTODv/0T/iWkLZwaBqDEy+ffHUkxqIDPV8H7kmK3L8kQBPg8tbb2CLhlm4IW4E0H3m9qBixgMwhAfoM5oGsSlUwdrxeNYA2vdiwiXe+MRtRgbEyKatjeJvkk/KNYiqy52EJhqYOCPdqeLYxdQfkq8IarPVYE3JtDGooTwO12eq336h8ewAJE9anjbOicAmKTGKruxINNlARL/wIXkbAWeHoKzFuo3GmvrhWk4lHeE/sJuvl1+giGpz+GVfUmnd+5JzoH5BbCzoCz7YVfLkPSsAQlmodgEhdisSxHMrGifQq/be8zwre7ZyyvSt364JJ6tCcTzsMEBQK/LGzAk5P97IzkTXQl0mdxp0UPV3vKqN+JxrPbHN3OyuhpcGCycjjVCpJymBI2rURP8tPxl8GXKu17DIcE7gGu7p5HeUyYNC95S/OpEUlCoG176aX1veRzfrkMVqSHMDfnspTvze/Tmgg4xleKKyp0NmfmaoOfLlttArXmoniPR+5LSeNYmX5HyahYRVxY9+YNfVKhN2xjTgxeGTU2HPlfkwDbIWPBDNUPdUDlV8BHK5PZKh/dVZuzxfJAxq8c5M460/oPjo+UIFs7CX+PUU67W+Tt/8wVs="
    - secure: "jqxrH5LW1HGZqRge7aJGI5e0o18FByExxoWx95ve3F4P5j73O4KwZ0EVHG3RzmdHqrH3ocUCe+KmrCsulH0G7/NVFKS5bIEJE6GS++B0S8ZOQXM/PYjlaViBAjoomxiF+UgCFdY8qRItAgSSZl/6Mu4XYJQAuz7MvlaYyET7IUrdU99LQYkR3EA+behFW6JVaPX5YFG+srsaxDLShy5ZB89cfI8+ERinfMHl7UC8GW/NH6WA0qtNt4VfZ4FB3gv4kXzpde/XNs+gduVMMEDyJG/+0EHokwWYRlGcf6j0Y6EYdIvAHTm/kOwJan5uYNlWhNFObsNt8loRAmKgYPKYDAG2pVoIInhdfTYOLc4ixm3C50pR/PaPYH+c/6e1vio+WtqlVcc+1mxrrsiE177tOHBqppw+rOvMMQE7TlRNyIx1LiWDDbPKwc8iPMTMX9VIsB2Stuhd6ApUP9GrCRYrE3jhFq1oZuhjDfqDQQLUFTuBYggIo6qdFNlYKH7BnsV8iZNSBXtTJrWVTI18naZc/lw8YI9fvKICTtxO7jdiwpD64rv0V1x1Vv40CML3eriZHXWnvbCmWG60he3rOYN85+kklW8ABTd02R+KsVN/6E9FgPfHuOxdgpwxZd1zjvjWVAKbd+KWJ1Mz8am+1Kgafnl2nnyHXBjjQOPG0ETkYNs="
    - secure: "N74vjhqHQ1r3xoEHU5bIlSciI7IVYaPj1R9Y/CgSGr2ivGCEcgq518R42byGbOBkhjf2DOL3Q9q/uTAvDJlN2RHeqMkNGOzRCuyD2FayUJx9QP13KZrQNeRxbXzJaHP+l5uab1xVJlWGuAa0ViXW5xaQnKUDIZOAo/ZZzF+4xH8GXkcABzZDXWEFB0nPHhBX+XW4aoRrzpSVsehyPkZfUmr3gOUbMp7avK8Ou0jMYAblU26JbfTB+kkky1Rv99jt7epv+LPhvEOmk8sK2DAeIoYw5f1jZpwXKR3bahiRynq/dSl/j8cC/pP5xRA3czB8vKFHpz2F7LEoJDG/J3wWhNwKM4gViBHZLTFBsoJfva20mwJFIN4xUvZyZX2BDIsQFoerzUCAugseyS8x9BwVD2/M1mS6nCIcu5LrLcnCw7PZSZL1xY9evAApJLGS1g6fBC9fzCi7pe/6Y5MD3aKdvbCwCpZnKdmx3vB7a0YQe4IG7qAbHWNnPIjSuMZiy9iuAGzbRjWEbC1WC7vRyS9Tx1LFkawDj/KaV1puJ2mE+R4bvhkMJ3GW0CWUp8aqniNLC/5IC8OWL5yo+R62E/xjzJr8DOEly4EOOMwvNSzL+FPX8Rh+q9fNrC3bl7bO9eIWaJ3XDEA/XHS4vrzJKX8aPkXpyc2i/JsMugvkdLIjeJM="
    - DISPLAY=:99.0
    - CXX=g++-4.8
    - MONGO_OPLOG_URL: "mongodb://localhost:27017/local"
    - MONGO_URL: "mongodb://localhost:27017/meteor"
    - TEST_MODE: "true"
    - TRAVIS_SECURE_ENV_VARS: "true"
